config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :command_executions, only: [:create]
  namespace :admin do
    resource :settings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  cache_prefix { "v1" }

  # Define your fields
  # field :host, type: :string, default: "http://localhost:3000"
  # field :default_locale, default: "en", type: :string
  # field :confirmable_enable, default: "0", type: :boolean
  # field :admin_emails, default: "admin@rubyonrails.org", type: :array
  # field :omniauth_google_client_id, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] || ""), type: :string, readonly: true
  # field :omniauth_google_client_secret, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] || ""), type: :string, readonly: true
  scope :magic_mirror do
    field :family_members,
      type: :hash,
      default: {
        dog: "Muffin",
        wife: "Dipti",
        husband: "Ankit"
      },
      validates: { presence: true }
  end

  scope :features do
    field :captcha_enable, type: :boolean, default: true
  end
end

app/controllers/admin/settings_controller.rb
module Admin
    class SettingsController < ApplicationController
      def new
      end

      def create
        @errors = ActiveModel::Errors.new(self)
        setting_params.keys.each do |key|
          next if setting_params[key].nil?
  
          setting = Setting.new(var: key)
          setting.value = setting_params[key].strip
          unless setting.valid?
            @errors.merge!(setting.errors)
          end
        end
  
        if @errors.any?
          render :new
        end

        setting_params.keys.each do |key|
          Setting.send("#{key}=", YAML.load(setting_params[key].strip)) unless setting_params[key].nil?
        end
  
        redirect_to new_admin_settings_path, notice: "Setting was successfully updated."
      end
  
      private
        def setting_params
          params.require(:setting).permit(:captcha_enable, :family_members)
        end
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/command_executions_controller.rb
class CommandExecutionsController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  def create
    # pi on -> vcgencmd display_power 1
    # pi off -> vcgencmd display_power 0
    success = system(params[:cmd])
    render json: {success: success}, status: 200
  end
end

app/controllers/magic_mirror_controller.rb
class MagicMirrorController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  def index
    # messages
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/command_execution_helper.rb
module CommandExecutionHelper
end

app/views/admin/create.html.erb
<%= form_for(Setting.new, url: admin_settings_path) do |f| %>
  <% if @errors.any? %>
    <div class="alert alert-block alert-danger">
      <ul>
        <% @errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group form-checkbox">
    <label>
      <%= f.check_box :captcha_enable, checked: Setting.captcha_enable? %>
      Enable/Disable Captcha
    </label>
  </div>

  <div class="form-group">
    <label class="control-label">Notification options</label>
    <%= f.text_area :family_members, value: YAML.dump(Setting.family_members), class: "form-control", style: "height: 180px;"  %>
    <div class="form-text">
      Use YAML format to config family_members
    </div>
  </div>

  <div>
    <%= f.submit 'Update Settings' %>
  </div>
<% end %>

app/views/admin/settings/new.html.erb
<%= form_for(Setting.new, url: admin_settings_path) do |f| %>
  <% if @errors&.any? %>
    <div class="alert alert-block alert-danger">
      <ul>
          <li><%= @errors.messages %></li>
      </ul>
    </div>
  <% end %>

  <div class="form-group form-checkbox">
    <label>
      <%= f.check_box :captcha_enable, checked: Setting.captcha_enable? %>
      Enable/Disable Captcha
    </label>
  </div>

  <div class="form-group">
    <label class="control-label">Family Members</label>
    <%= f.text_area :family_members, value: YAML.dump(Setting.family_members), class: "form-control", style: "height: 180px;"  %>
    <div class="form-text">
      Use YAML format to config family_members
    </div>
  </div>

  <div>
    <%= f.submit 'Update Settings' %>
  </div>
<% end %>

app/views/admin/settings/show.html.erb
<%= form_for(Setting.new, url: admin_settings_path) do |f| %>
  <% if @errors.any? %>
    <div class="alert alert-block alert-danger">
      <ul>
        <% @errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group form-checkbox">
    <label>
      <%= f.check_box :captcha_enable, checked: Setting.captcha_enable? %>
      Enable/Disable Captcha
    </label>
  </div>

  <div class="form-group">
    <label class="control-label">Notification options</label>
    <%= f.text_area :family_members, value: YAML.dump(Setting.family_members), class: "form-control", style: "height: 180px;"  %>
    <div class="form-text">
      Use YAML format to config family_members
    </div>
  </div>

  <div>
    <%= f.submit 'Update Settings' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PiController</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/magic_mirror.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PiController</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>